# Copyright (c) 2025 Mr. J.W. Swain - 3000 Studios. All Rights Reserved.
# Unauthorized copying, modification, distribution, or use of this is prohibited without express written permission.

# Copilot Ωmega Workspace Configuration
# This file configures GitHub Copilot behavior for the 3000 Studios Theme repository

name: "3000 Studios Theme - Copilot Ωmega"
version: "1.0.0"

# Project Context
context:
  type: "wordpress-theme"
  framework: "custom"
  languages:
    - "php"
    - "javascript"
    - "css"
    - "html"
  
  dependencies:
    - "WordPress 5.8+"
    - "Tailwind CSS"
    - "Framer Motion"
    - "Three.js"

# Coding Standards
standards:
  php:
    style: "WordPress Coding Standards"
    version: "7.4+"
    security: "strict"
    
  javascript:
    style: "ESLint"
    ecmaVersion: "ES2021"
    modules: true
    
  css:
    framework: "Tailwind CSS"
    style: "utility-first"
    
  documentation:
    style: "JSDoc"
    required: true

# Security Rules
security:
  - "Always sanitize user inputs"
  - "Use nonce verification for forms"
  - "Escape all outputs"
  - "Use prepared statements for database queries"
  - "Never expose credentials in code"
  - "Implement proper error handling"

# Monetization Patterns
monetization:
  payments:
    - "Stripe"
    - "PayPal"
    - "Cash App"
  
  analytics:
    - "Google Analytics"
    - "Custom tracking"
  
  seo:
    enabled: true
    structured_data: true

# Brand Guidelines
brand:
  name: "3000 Studios"
  theme: "neon-futuristic"
  
  colors:
    primary: "#00ffff"    # Cyan
    secondary: "#9d4edd"  # Purple
    accent: "#00ff00"     # Lime
    background: "#0a0a0a" # Dark
    
  typography:
    heading: "Orbitron"
    body: "Rajdhani"
    
  animations:
    duration: "300-500ms"
    easing: "ease-in-out"
    fps: 60

# File Patterns
patterns:
  wordpress_page_template:
    prefix: "page-"
    suffix: ".php"
    location: "root"
    
  javascript:
    location: "js/"
    minified: false
    
  styles:
    location: "assets/css/"
    preprocessor: "none"

# Ignore Patterns
ignore:
  - "node_modules/"
  - "vendor/"
  - "*.min.js"
  - "*.min.css"
  - ".git/"
  - "*.zip"

# Custom Commands
commands:
  - name: "Create WordPress Page Template"
    pattern: "// @copilot-omega create-page-template [name]"
    
  - name: "Add Neon Animation"
    pattern: "/* @copilot-omega neon-animation */"
    
  - name: "Integrate Payment"
    pattern: "// @copilot-omega add-payment [provider]"
    
  - name: "SEO Optimization"
    pattern: "// @copilot-omega optimize-seo"

# Learning Preferences
learning:
  adapt_to_codebase: true
  suggest_refactoring: true
  auto_fix_issues: true
  performance_optimization: true

# Deployment
deployment:
  environments:
    - "development"
    - "staging"
    - "production"
  
  platforms:
    - "WordPress"
    - "Vercel"
    - "cPanel"

# Testing
testing:
  unit_tests: false
  integration_tests: false
  manual_testing: true

# Version Control
vcs:
  platform: "GitHub"
  default_branch: "main"
  commit_style: "conventional"
  
# Collaboration
collaboration:
  team: "3000 Studios"
  owner: "Mr. J.W. Swain"
  
# Quality Metrics
quality:
  code_coverage: 0
  performance_score: 95
  security_score: 100
  accessibility_score: 90
