name: Deploy WordPress Theme via SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create theme ZIP with timestamp
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
          THEME_NAME="3000studios-$(date -u +"%Y%m%d-%H%M%S")"
          echo "THEME_NAME=${THEME_NAME}" >> $GITHUB_ENV
          echo "BUILD_TIME=${TIMESTAMP}" >> $GITHUB_ENV
          
          # Update style.css with build timestamp
          sed -i "s/{{BUILD_TIME}}/${TIMESTAMP}/g" style.css
          
          # Create ZIP
          zip -r ${THEME_NAME}.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "node_modules/*" \
            -x ".DS_Store" \
            -x "README*.md" \
            -x "SETUP_COMPLETE.md" \
            -x "QUICKSTART.md" \
            -x "scripts/*" \
            -x "webhook-server/*" \
            -x "mobile-client/*"
          ls -lh ${THEME_NAME}.zip
          echo "✓ Created: ${THEME_NAME}.zip (Built: ${TIMESTAMP})"

      - name: Upload theme ZIP via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.WP_SSH_HOST }}
          username: ${{ secrets.WP_SSH_USER }}
          password: ${{ secrets.WP_SSH_PASSWORD }}
          port: ${{ secrets.WP_SSH_PORT }}
          source: "${{ env.THEME_NAME }}.zip"
          target: "/tmp/"
          overwrite: true

      - name: Extract theme on server
        uses: appleboy/ssh-action@v1.0.3
        env:
          THEME_NAME: ${{ env.THEME_NAME }}
        with:
          host: ${{ secrets.WP_SSH_HOST }}
          username: ${{ secrets.WP_SSH_USER }}
          password: ${{ secrets.WP_SSH_PASSWORD }}
          port: ${{ secrets.WP_SSH_PORT }}
          envs: THEME_NAME
          script: |
            # Navigate to themes directory
            cd /clickandbuilds/3000Studios/wp-content/themes
            
            echo "Deploying new theme: ${THEME_NAME}"
            
            # Extract new theme with timestamped name
            mkdir -p ${THEME_NAME}
            unzip -o /tmp/${THEME_NAME}.zip -d ${THEME_NAME}
            
            # Set proper permissions
            chmod -R 755 ${THEME_NAME}
            
            # Cleanup
            rm /tmp/${THEME_NAME}.zip
            
            # List all 3000studios themes with timestamps
            echo ""
            echo "=== All 3000 Studios Themes ==="
            ls -lht | grep "3000studios" | head -10
            echo ""
            echo "✓ Theme deployed successfully: ${THEME_NAME}"
            echo "✓ Activate it in WordPress: Appearance > Themes > ${THEME_NAME}"
